export const PRODUCTS = [
  {
    title: "Coca-cola",
    imageUrl: "https://i.ibb.co/smWdgQR/MAT-1351912-PCE-EE.jpg",
    cod: "A1",
    price: 3,
    amount: 5,
  },
  {
    title: "Coca-cola",
    imageUrl: "https://i.ibb.co/smWdgQR/MAT-1351912-PCE-EE.jpg",
    cod: "A2",
    price: 3,
    amount: 5,
  },
  {
    title: "Coca-cola",
    imageUrl: "https://i.ibb.co/smWdgQR/MAT-1351912-PCE-EE.jpg",
    cod: "A3",
    price: 3,
    amount: 5,
  },
  {
    title: "Pepsi",
    imageUrl: "https://i.ibb.co/qpxJDhx/61-Q7-SR0r9-XL-SL1500.jpg",
    cod: "B1",
    price: 2,
    amount: 5,
  },
  {
    title: "Pepsi",
    imageUrl: "https://i.ibb.co/qpxJDhx/61-Q7-SR0r9-XL-SL1500.jpg",
    cod: "B2",
    price: 2,
    amount: 5,
  },
  {
    title: "Pepsi",
    imageUrl: "https://i.ibb.co/qpxJDhx/61-Q7-SR0r9-XL-SL1500.jpg",
    cod: "B3",
    price: 2,
    amount: 5,
  },
  {
    title: "M&M",
    imageUrl: "https://i.ibb.co/r6qKPpp/640x640.jpg",
    cod: "C1",
    price: 7,
    amount: 5,
  },
  {
    title: "M&M",
    imageUrl: "https://i.ibb.co/r6qKPpp/640x640.jpg",
    cod: "C2",
    price: 7,
    amount: 5,
  },
  {
    title: "M&M",
    imageUrl: "https://i.ibb.co/r6qKPpp/640x640.jpg",
    cod: "C3",
    price: 7,
    amount: 5,
  },
];
